typedef struct lista *Lista;
Lista cria_lista();
int lista_vazia(Lista lst);
int lista_cheia(Lista lst);
int insere_elem(Lista lst, int elem);
int remove_elem(Lista lst, int elem);
void imprime(Lista lst);
int tamanho(Lista lst);
int menor(Lista lst);
int remove_impar(Lista lst);
Lista ordena(Lista lst);
Lista concatena(Lista lst_a, Lista lst_b);
int escolhe_lst(void);
